### ISSUE TITLE
Problem with loading json

### ISSUE THREAD

**Issue by Balgorinfo** [jexp/neo4j-apoc-procedures#1]
I have a problem with the second part of the loadJson. I works to load the Json using:

CALL apoc.util.loadJson('http://localhost/result.json')

But if I add the part starting with YIELD... I get the following error:

Invalid input 'Y': expected whitespace, comment, ';' or end of input (line 1, column 57 (offset: 56))
"CALL apoc.util.loadJson('http://localhost/result.json') YIELD value as person"

Regards

G.

**Comment by jexp** [comment]
Which Neo4j version do you use? Make sure to use the one from alpha.neohq.net or a snapshot. Or wait for RC1
